
language: c
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

matrix:
  include:
    # - env: BUILD=cabal CABALVER=1.24 GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
    #   compiler: ": #GHC 7.8.4"
    #   addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4], sources: [hvr-ghc]}}
    #
    # - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3
    #   compiler: ": #GHC 7.10.3"
    #   addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    #
    # - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.1
    #   compiler: ": #GHC 8.0.1"
    #   addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

    - env: BUILD=stack GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
      compiler: ": #stack 7.8.4"
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3 osx"
      os: osx

    - env: BUILD=stack GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
      compiler: ": #stack 8.0.1"
      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - chmod a+x ~/.local/bin/stack

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - case "$BUILD" in
     stack)
       stack --no-terminal test;;
     cabal)
       cabal --version;
       travis_retry cabal update;
       cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1;;
   esac

install:
  - stack -j 2 setup --no-terminal
  - stack -j 2 build --only-snapshot --no-terminal

script:
  - stack -j 2 test --no-terminal

#
# script:
#  - set -e; case "$BUILD" in
#      stack)
#        stack --no-terminal test --ghc-options="-Werror";;
#      cabal)
#        cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror";
#        cabal build;
#        cabal test;
#        cabal check;
#    esac
